---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: learn-argocd
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: Kubectl Scripts/fleetapplication
    repoURL: 'https://github.com/Rakesh459/istiopoc.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: learn-addons
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: samples/addons
    repoURL: 'https://github.com/Rakesh459/istio.git'
    targetRevision: release-1.20
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
