apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio-ingressgateway
  name: istio-ingressgateway
  namespace: istio-system
spec:
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: http3
    port: 8090
    protocol: TCP
    targetPort: 8090
  - name: http4
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: http5
    port: 10000
    protocol: TCP
    targetPort: 10000
  - name: http6
    port: 11000
    protocol: TCP
    targetPort: 11000
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: LoadBalancer
