apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-wi # needs to be unique per namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" 
    userAssignedIdentityID: "*******" # Setting this to use workload identity
    keyvaultName: "keyvaluename"     # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: MySecret             # Set to the name of your secret
          objectType: secret              # object types: secret, key, or cert
          objectVersion: "" 
    tenantId: "*******" 
  secretObjects:  
  - data:
    - objectName: MySecret
      key: my-secret
    secretName: my-secret
    type: Opaque
