apiVersion: v1
kind: Secret
metadata:
  name: my-tls-secret
  namespace: istio-system
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVyakNDQTVhZ0F3SUJBZ0lVQ2QxRHJROGc3
    cWgrejFrQ2g4bXJlN2orWTgwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZc3hDekFKQmdOVkJBWVRB
    bFZUTVJrd0Z3WURWUVFLRXhCRGJHOTFaRVpzWVhKbExDQkpibU11TVRRdwpNZ1lEVlFRTEV5dERi
    RzkxWkVac1lYSmxJRTl5YVdkcGJpQlRVMHdnUTJWeWRHbG1hV05oZEdVZ1FYVjBhRzl5CmFYUjVN
    Ull3RkFZRFZRUUhFdzFUWVc0Z1JuSmhibU5wYzJOdk1STXdFUVlEVlFRSUV3cERZV3hwWm05eWJt
    bGgKTUI0WERUSTBNRGN4TVRBNE5UZ3dNRm9YRFRNNU1EY3dPREE0TlRnd01Gb3dZakVaTUJjR0Ex
    VUVDaE1RUTJ4dgpkV1JHYkdGeVpTd2dTVzVqTGpFZE1Cc0dBMVVFQ3hNVVEyeHZkV1JHYkdGeVpT
    QlBjbWxuYVc0Z1EwRXhKakFrCkJnTlZCQU1USFVOc2IzVmtSbXhoY21VZ1QzSnBaMmx1SUVObGNu
    UnBabWxqWVhSbE1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXVR
    UzRJQndLVFVtQzRtYThiZDNsU1BnNFBnQ05lSDVDMFBFbwpVUzZYd2tqZ2xWNC9yaU84UkF1Q0xq
    dWlUd25QcHNBV3hKbXZqSGoxeHNTZEpwYmhwZGF1QVpvNUViQzBCOTl6CmdST2FEVU55SzVBTTFl
    TWlUQnFxSjBUVmFZaGt2cGVJZ2JuZXA5OVVrYWlIUVk3QnZIQ0toT1lyOHlleTB4QTkKVldsK001
    dmw1Q21xV1diNUMyTDd3ZlIvTUFvalpFb2Z0WkVVRE9seFpGb3gvRC9VS2RIYVBIbUdsdWhYNno5
    ZApKODdkTkY0cmFhQTVrN000QTJYaHNMQXMwY2tpOTdtcmU3VTZVSjNLSkEvTHY0NkJoOWxoODI2
    WEkrNXlEaUxrCmx4b2toVGtkVzFoa3lZSFVqM0RUcjlIQzBtbmRqQUpEeHpHYk1oU1FqQ3N5VHVZ
    WWRRSURBUUFCbzRJQk1EQ0MKQVN3d0RnWURWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWRKUVFXTUJR
    R0NDc0dBUVVGQndNQ0JnZ3JCZ0VGQlFjRApBVEFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdR
    V0JCVCtYUHZiVG9XMnhpSkdlM1Z0ZnBua0lvSmRGakFmCkJnTlZIU01FR0RBV2dCUWs2Rk5YWFh3
    MFFJZXA2NVRidXVFV2VQd3BwREJBQmdnckJnRUZCUWNCQVFRME1ESXcKTUFZSUt3WUJCUVVITUFH
    R0pHaDBkSEE2THk5dlkzTndMbU5zYjNWa1pteGhjbVV1WTI5dEwyOXlhV2RwYmw5agpZVEF4QmdO
    VkhSRUVLakFvZ2hNcUxuSmhhMlZ6YUhSbGMzUnBibWN1ZUhsNmdoRnlZV3RsYzJoMFpYTjBhVzVu
    CkxuaDVlakE0QmdOVkhSOEVNVEF2TUMyZ0s2QXBoaWRvZEhSd09pOHZZM0pzTG1Oc2IzVmtabXho
    Y21VdVkyOXQKTDI5eWFXZHBibDlqWVM1amNtd3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRHU1
    dndwcFFaNW1YbFNYZHk2aQptVEdQYk5QWXU0aS9WR1VkazJ5U2JVOWhCUTc5d2VlRW5sNitvMjZL
    bStsa3ZhR2QxQUFrK1htbW9iNDFBUitICmMrSDAxYW9QUDVoeEhHMHI3Y3dWRkxhVWVLdnE5bWJh
    SmFmZk9xZytjMkZmSU43YXNieTYzbzdOeW5rOE1nOGYKdGVwTkUrdE9VVFB1MzdhUnJKWWQ4ay9j
    dEFuSC84amJycFRBSkR5VzZGTHlZVktRZk1PU2JYb3ViQTdDclZhMQpVSEhnV0dyZnFsRTJCaWUw
    SEFtbXR5S1V4dDE4bWY5MnRuOWo3LzBmelp4REZmVzVveEx4M0w5VjRIQkpENjFFCnQzN0grWllx
    NnJEaXFBTHo3d2NLYmVZV1lWMFo3d2ZhUU12NWJ6dHk5c3lhbG83Y1lyU1VXSysyQTh5NHlGeXMK
    bDIwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktnd2dnU2tBZ0VBQW9JQkFRQzVCTGdnSEFwTlNZTGkKWnJ4dDNlVkkrRGcrQUkxNGZrTFE4
    U2hSTHBmQ1NPQ1ZYait1STd4RUM0SXVPNkpQQ2MrbXdCYkVtYStNZVBYRwp4SjBtbHVHbDFxNEJt
    amtSc0xRSDMzT0JFNW9OUTNJcmtBelY0eUpNR3FvblJOVnBpR1MrbDRpQnVkNm4zMVNSCnFJZEJq
    c0c4Y0lxRTVpdnpKN0xURUQxVmFYNHptK1hrS2FwWlp2a0xZdnZCOUg4d0NpTmtTaCsxa1JRTTZY
    RmsKV2pIOFA5UXAwZG84ZVlhVzZGZnJQMTBuenQwMFhpdHBvRG1Uc3pnRFplR3dzQ3pSeVNMM3Vh
    dDd0VHBRbmNvawpEOHUvam9HSDJXSHpicGNqN25JT0l1U1hHaVNGT1IxYldHVEpnZFNQY05PdjBj
    TFNhZDJNQWtQSE1ac3lGSkNNCkt6Sk81aGgxQWdNQkFBRUNnZ0VBQ0lCMmc0YzJVL25hU1ZRR09a
    ZzJOb1d0YysvcmtFdGcvNS90UmRtNXdJUS8KeWExVWlNaDhtTFhjckFveWVhWk9RKy9VdkFFQjU1
    Y1JXQ3BsdkVXM3BicTVNVHFvZjY4YWZyZ2VZeUtHOURBUwp1WHk3a2tLSEsyOFlQWWkwczg1QUx0
    L2d0bkZYa1dnNlJ4MHk1ZWpNN3o5T3BpKzdla2RyT0xhbzB0bHZvcWhsCnhoQ0VvVGFBYkZNRWFo
    Qi9RalNLdXp5L1l1K25zS3lVck93VkhqZHV0Zm1mM2VMQ3lyUXVRK29OQjZINzRiMGkKVkJORk9S
    TTVkYjNwRHdRSFA3UzdUSnJDTXMxTTIxTkViMkhGeURkcWhXUjQ2MnhmVXRreVRwd0wxUHI5d1Q5
    bwpNbXZpb25LRmRIcTFOc21TZmdBYWRTNkJWOTM1emVkbFJlUXhKemNpWVFLQmdRRGFpNE9uQksz
    aGFvb1VpNUhUCmdnZTdzM1krWWNnbURsdmE5RGRCMHg2K0g5VkYvTDhqekFDYmRpMmMxVUtReHdt
    RU5XVVVrZ2pTVVJWTnlvay8KZVVyT3NkeFZqUi82ei9tWCthWnlUQ2ZYVCtxc1BvWWdnNHBHV1Jn
    aUJucmNtak5oa3JNRmFXc0Q3b2paSW5oVwpzZnF3MTRyb3YwdkhjNUg2Ujd0Q01oV3gwUUtCZ1FE
    WXVrRTRXeUZCNUU1SE9MQXJnNFhLR3d2WTJubkc1OHBoCmVtYUVBWGdPRG1EbXYzRGh3UmJWT3Bt
    T01lZHM0WWpYampQNmhCSlEzMkUyc2RLVHhUZzlkbHMvbk1OdnBnaTgKMTdsZXVPQzNKK2k3bE1B
    Yk9ZZlJjaHh5VU12dXJySWlKYmpnaEJPWHpRMi9nODNiM09OQmdlNjBOdXdhWlVjYgo5YTVKZ1hz
    aFpRS0JnUUNMRnV2dEtrODMvY1J2bXZ4dWJuMVplcmd3cjY3Z2VaY0FYUm1sN1NYTnZ4alBlREoy
    CkorbmpCMjIwT1E0cWNtS2VJQlY2NkE1eFBHV2dvdHlDNTBFekY0T3hkeVg1VE0vL1owWUZ6RzQy
    M0lmd284SmQKZ3hwSDk0QWlkNWxPT1YybUplV0Y5amZEd3RhWnl4Um5xTkp5Smx3a0VVdTdYdFJ6
    UTUvc1cwL3ZZUUtCZ0c1MwpJTjhVcy9MZDUzZ3QwTDJkSUFoUG1NNURMV2JRcGpyaEpIZU1PQ0VS
    K3hvaDRldHZlNi9iV29FN3RuV3N6dzd2CmtGYlVFbkhlS2JLekdGM3hYQ1VYdXBMRjJHZUQvVmdq
    ckh3M1IzS1RpUEJ6ZFNkclAycmwrdEhabE5obmVxd2wKQmdLSnoyTEVSWW1rS0wwejdURnFoTHll
    Y2VGU1ZkaE9kVE5LSi9SeEFvR0JBTkJyVnBhTzFSYjBpSEtNVk16RwpORTVYNWVLc3VyUzdNK2xr
    RldhbTk1MHhJNVl4NVB1aUJVN3VEVy8zNUNES28vMklXRGdyOStQSnJnQ0J5Z1ZEClhtTWlDaXZk
    VVhwbTVVNHMzaFRMNGpDRS9rb2J5emh5U0RMTHVPeXpNdWhNdEVTWU9VWWl4K3ZFdmVPVDdFZ2MK
    Tlo4R0VRZ0N0dXE5b2pOWngwS0xRWXVTCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
